FROM node:18-alpine3.17

WORKDIR /app

EXPOSE 8080

RUN corepack prepare yarn@3.5.1 --activate

COPY ./backend .
COPY ./backend/.env ./.env
COPY ./backend/package.json .

RUN yarn

EXPOSE $BE_PORT

CMD ["yarn", "start:dev"]