export const QUERY_KEYS = {
  RECIPES: "RECIPES",
  BY_CATEGORY: "BY_CATEGORY",
  BY_REGION: "BY_REGION",
  BY_INGRIDIENT: "BY_INGRIDIENT",
  RECIPE: "RECIPE",
  CATEGORIES: "CATEGORIES",
  REGIONS: "REGIONS",
  INGRIDIENTS: "INGRIDIENTS",
};
